export enum ObjectType {
    CaseContact = 'CaseContact',
    CaseInterview = 'CaseInterview',
    CaseCourtDate = 'CaseCourtDate',
    CaseCVCApplication = 'CaseCVCApplication',
    CaseDocument = 'CaseDocument',
    CaseEmergencyContact = 'CaseEmergencyContact',
    CaseIncident = 'CaseIncident',
    CaseLetter = 'CaseLetter',
    CaseNote = 'CaseNote',
    CaseOffender = 'CaseOffender',
    CasePayment = 'CasePayment',
    CasePolice = 'CasePolice',
    CaseProtectiveOrder = 'CaseProtectiveOrder',
    CaseReferral = 'CaseReferral',
    CaseService = 'CaseService',
    CaseVictimization = 'CaseVictimization',
    CaseWitness = 'CaseWitness',
    ServiceProgram = 'ServiceProgram'
}

export enum CaseAPIEndpoints {
    ContactLog = 'contacts',
    CourtDates = 'courtdates',
    CVCApplications = 'cvcapplications',
    Documents = 'documents',
    EmergencyContacts = 'emergencycontacts',
    Incidents = 'incidents',
    Interviews = 'interviews',
    Letters = 'letters',
    Notes = 'notes',
    Offenders = 'offenders',
    Payments = 'payments',
    Police = 'police',
    ProtectiveOrders = 'protectiveorders',
    Referrals = 'referrals',
    ServicesProvided = 'services',
    Victimizations = 'victimizations',
    Witnesses = 'witnesses'
}

export enum ValueTitles {
    agegroupings = 'Age Groupings',
    applicationstatuses = 'Application Statuses',
    bondtypes = 'Bond Types',
    contacttypes = 'Contact Types',
    documenttypes = 'Document Types',
    referraltypes = 'Referral Types',
    servicecategories = 'Service Categories',
    servicepopulations = 'Service Populations',
    serviceprograms = 'Service Programs',
    countries = 'Countries',
    dockettypes = 'Docket Types',
    ethnicities = 'Ethnicities',
    firecauses = 'Fire Causes',
    genders = 'Genders',
    interviewerpositions = 'Interviewer Positions',
    interviewdocumentationtypes = 'Interview Documentation Types',
    languages = 'Languages',
    lettertypes = 'Letter Types',
    locationtypes = 'Location Types',
    offenses = 'Offenses',
    offensetypes = 'Offense Types',
    orderstatuses = 'Order Statuses',
    ordertypes = 'Order Types',
    organizationtypes = 'Organization Types',
    paymentcategories = 'Payment Categories',
    payors = 'Payors',
    races = 'Races',
    relationshiptypes = 'Relationship Types',
    states = 'States',
    statuses = 'Statuses',
    victimtypes = 'Victim Types'
}

export enum ValueAPIEndpoints {
    agegroupings = 'api/AgeGroupings',
    applicationstatuses = 'api/ApplicationStatuses',
    bondtypes = 'api/BondTypes',
    contacttypes = 'api/ContactTypes',
    documenttypes = 'api/DocumentTypes',
    referraltypes = 'api/ReferralTypes',
    servicecategories = 'api/ServiceCategories',
    servicepopulations = 'api/ServicePopulations',
    serviceprograms = 'api/ServicePrograms',
    countries = 'api/Countries',
    dockettypes = 'api/DocketTypes',
    ethnicities = 'api/Ethnicities',
    firecauses = 'api/FireCauses',
    genders = 'api/Genders',
    interviewerpositions = 'api/InterviewerPositions',
    interviewdocumentationtypes = 'api/InterviewDocumentationTypes',
    languages = 'api/Languages',
    lettertypes = 'api/LetterTypes',
    locationtypes = 'api/LocationTypes',
    offenses = 'api/Offenses',
    offensetypes = 'api/OffenseTypes',
    orderstatuses = 'api/OrderStatuses',
    ordertypes = 'api/OrderTypes',
    organizationtypes = 'api/OrganizationTypes',
    paymentcategories = 'api/PaymentCategories',
    payors = 'api/Payors',
    races = 'api/Races',
    relationshiptypes = 'api/RelationshipTypes',
    states = 'api/States',
    statuses = 'api/Statuses',
    victimtypes = 'api/VictimTypes'
}
